##HomeR

# We don't actually use this first one because we need to style Well Typed.
Welcome: Welcome to Well Typed!

AlphaHeader: Public Alpha

Alpha: We are currently in a Public Alpha.

MissingFeatures: This means that some of the features that we want the site to have aren't yet ready to be tested by our users.

AlphaFeatures: However, we still have a lot to offer you! Currently, there is a growing guide on how to build a website just like this!

YesodGuideButton: Start Reading

OtherThingsToDo: In addition to that, you can post your own guides and examples, as well as edit other people's contributions. All you need to do is Register.

Register: We won't even email you, don't worry.

RegisterButton: Register Here

Documentation: To see a list of our current documentation
